services:
  database:
    image: postgres:16-alpine
    container_name: mainservice-db
    environment:
      - POSTGRES_DB=mainservice_db
      - POSTGRES_USER=mainservice_user
      - POSTGRES_PASSWORD=mainservice_pass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mainservice:
    build: .
    container_name: mainservice-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/mainservice_db
      SPRING_DATASOURCE_USERNAME: mainservice_user
      SPRING_DATASOURCE_PASSWORD: mainservice_pass
    depends_on:
      - database

volumes:
  db_data:

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.2
    container_name: mainservice-keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=keycloak_pass
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ['start-dev']
    ports:
      - '8081:8080'
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:16-alpine
    container_name: keycloak-db
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak_user
      - POSTGRES_PASSWORD=keycloak_pass
    volumes:
      - keycloak_data:/var/lib/postgresql/data

volumes:
  keycloak_data:
